<?php
	$config['PUSHER_APP_KEY'] = 'YOUR_PUSHER_APP_KEY';
	$config['PUSHER_APP_SECRET'] = 'YOUR_PUSHER_APP_SECRET';
	$config['PUSHER_APP_ID'] = 'YOUR_PUSHER_APP_ID';
	$config['PUSHER_APP_CLUSTER'] = 'YOUR_PUSHER_APP_CLUSTER';
?>